DROP SCHEMA IF EXISTS db CASCADE;
DROP SCHEMA IF EXISTS dictionary CASCADE;
DROP SCHEMA IF EXISTS security CASCADE;
CREATE SCHEMA IF NOT EXISTS db;
CREATE SCHEMA IF NOT EXISTS dictionary;
CREATE SCHEMA IF NOT EXISTS security;
