application:
  cache:
    page-all-record-view:
      entries: 100
      ttl-ms: 360000
  db:
    username: ${DB_USER:dbuser}
    password: ${DB_PASS:password}
    r2dbc:
      host-rw: ${MASTER_DB_HOST:localhost}
      host-ro: ${CLUSTER_DB_HOST:localhost}
      port-rw: ${MASTER_DB_PORT:5432}
      port-ro: ${CLUSTER_DB_PORT:5432}
      database: ${DB_NAME:db}
      pool:
        connect-timeout: 500
        validation-depth: REMOTE
        validation-query: "SELECT 1"
  reactive:
    buffer-size: 128
    duration: 30000
    limit: 1000

logging:
  level:
    ROOT: INFO
    io:
      r2dbc:
        h2: INFO
    org:
      springframework:
        core:
          codec:
            CharSequenceEncoder: INFO
        web:
          server:
            session:
              DefaultWebSessionManager: INFO
            adapter:
              HttpWebHandlerAdapter: INFO
      thymeleaf:
        TemplateEngine: INFO
    su:
      svn:
        daybook: DEBUG

management:
  endpoint:
    caches:
      enabled: true
    health:
      group:
        custom:
          include: diskSpace,ping
          show-details: when_authorized
          show-components: when_authorized
      enabled: true
      show-details: when_authorized
      show-components: when_authorized
    info:
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
  health:
    db:
      enabled: true
    defaults:
      enabled: false
    ldap:
      enabled: false
    livenessstate:
      enabled: true
    ping:
      enabled: true

server:
  compression:
    enabled: true

spring:
  jackson:
    date-format: "yyyy-MM-dd'T'HH:mm:ss[.SSS][.SS][.S][X]"
    serializer-date-time-format: "yyyy-MM-dd'T'HH:mm:ss.SS+00:00"
    default-property-inclusion: non_null
    serialization:
      write_dates_as_timestamps: false
  r2dbc:
    url: ${DB_URL:r2dbc:postgresql://localhost/db}
    username: ${DB_USER:dbuser}
    password: ${DB_PASS:password}
  main:
    allow-bean-definition-overriding: true
  thymeleaf:
    reactive:
      max-chunk-size: 8192
  webflux:
    static-path-pattern: '/**'
    format:
      date-time: yyyy-MM-dd HH:mm:ss
      time: HH:mm:ss
      date: yyyy-MM-dd
  mvc:
    favicon:
      enabled: true
    format:
      date-time: yyyy-MM-dd HH:mm:ss
      date: yyyy-MM-dd
      time: HH:mm:ss

springbootwebfluxjjwt:
  jjwt:
    secret: ThisIsSecretForJWTHS512SignatureAlgorithmThatMUSTHave64ByteLength
    expiration: 28800
  password:
    encoder:
      secret: mysecret
      iteration: 33
      keylength: 256
