application:
  db:
    username: ${DB_USER:dbuser}
    password: ${DB_PASS:password}
    r2dbc:
      host-rw: ${MASTER_DB_HOST:localhost}
      host-ro: ${CLUSTER_DB_HOST:localhost}
      port-rw: ${MASTER_DB_PORT:3306}
      port-ro: ${CLUSTER_DB_PORT:3306}
      database: ${DB_NAME:db}
      pool:
        connect-timeout: 500
        duration: 30000
        validation-depth: REMOTE
        validation-query: "SELECT 1"
  reactive:
    buffer-size: 128
    duration: 30000
    limit: 1000
  security:
    strength: 12

logging:
  level:
    ROOT: INFO

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost/db
    username: dbuser
    password: password